FROM armhf/alpine:latest

RUN adduser -h /home/media -D media

COPY install.sh install.sh
RUN sh install.sh

EXPOSE 8081
USER media
VOLUME /home/sickrage
VOLUME /mnt/media

ENTRYPOINT ["python", "/usr/share/sickrage/SickBeard.py", "--datadir=/home/media" ]

